[project]
name = "perplexity-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.3.0",
    "openai>=1.65.4",
    "python-dotenv>=1.0.1",
]
